version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: mybasedb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"